export default {
  LOGIN: {
    // CHANGE_VALUE: 'LOGIN_CHANGE_VALUE',
    AUTH: "LOGIN_AUTH",
    LOGOUT: "LOGOUT_AUTH",
  },
  CONTRACTCODE: "CONTRACTCODE",
  SET: {
    ITEM: "SET_ITEM",
    CLIENT: "SET_CLIENT",
  },
  CLEAR: {
    ITEM: "CLEAR_ITEM",
    CLIENT: "CLEAR_CLIENT",
  },
};
